#ifndef CYCALESS_SRC_VERSION_H_
#define CYCALESS_SRC_VERSION_H_

#define CYCALESS_VERSION_MAJOR 1
#define CYCALESS_VERSION_MINOR 0
#define CYCALESS_VERSION_MICRO 0

#endif  // CYCALESS_SRC_VERSION_H_
